// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: proto/content.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PageTocItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title string         `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Items []*PageTocItem `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *PageTocItem) Reset() {
	*x = PageTocItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_content_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageTocItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageTocItem) ProtoMessage() {}

func (x *PageTocItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageTocItem.ProtoReflect.Descriptor instead.
func (*PageTocItem) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{0}
}

func (x *PageTocItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PageTocItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PageTocItem) GetItems() []*PageTocItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type PageContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title string         `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Html  string         `protobuf:"bytes,3,opt,name=html,proto3" json:"html,omitempty"`
	Toc   []*PageTocItem `protobuf:"bytes,4,rep,name=toc,proto3" json:"toc,omitempty"`
}

func (x *PageContent) Reset() {
	*x = PageContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_content_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageContent) ProtoMessage() {}

func (x *PageContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageContent.ProtoReflect.Descriptor instead.
func (*PageContent) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{1}
}

func (x *PageContent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PageContent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PageContent) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

func (x *PageContent) GetToc() []*PageTocItem {
	if x != nil {
		return x.Toc
	}
	return nil
}

type Page struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title        string  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Parent       string  `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	ParentId     string  `protobuf:"bytes,4,opt,name=parentId,proto3" json:"parentId,omitempty"`
	Level        int32   `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	Type         string  `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Link         string  `protobuf:"bytes,7,opt,name=link,proto3" json:"link,omitempty"`
	Extern       bool    `protobuf:"varint,8,opt,name=extern,proto3" json:"extern,omitempty"`
	Pages        []*Page `protobuf:"bytes,9,rep,name=pages,proto3" json:"pages,omitempty"`
	Data         string  `protobuf:"bytes,10,opt,name=data,proto3" json:"data,omitempty"`
	Show         bool    `protobuf:"varint,20,opt,name=show,proto3" json:"show,omitempty"`
	ActiveParent bool    `protobuf:"varint,21,opt,name=activeParent,proto3" json:"activeParent,omitempty"`
}

func (x *Page) Reset() {
	*x = Page{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_content_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{2}
}

func (x *Page) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Page) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Page) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *Page) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Page) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Page) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Page) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Page) GetExtern() bool {
	if x != nil {
		return x.Extern
	}
	return false
}

func (x *Page) GetPages() []*Page {
	if x != nil {
		return x.Pages
	}
	return nil
}

func (x *Page) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Page) GetShow() bool {
	if x != nil {
		return x.Show
	}
	return false
}

func (x *Page) GetActiveParent() bool {
	if x != nil {
		return x.ActiveParent
	}
	return false
}

type Options struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accordion bool `protobuf:"varint,1,opt,name=accordion,proto3" json:"accordion,omitempty"`
}

func (x *Options) Reset() {
	*x = Options{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_content_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{3}
}

func (x *Options) GetAccordion() bool {
	if x != nil {
		return x.Accordion
	}
	return false
}

type Navi struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Header      []*Page  `protobuf:"bytes,4,rep,name=header,proto3" json:"header,omitempty"`
	Footer      []*Page  `protobuf:"bytes,5,rep,name=footer,proto3" json:"footer,omitempty"`
	Pages       []*Page  `protobuf:"bytes,6,rep,name=pages,proto3" json:"pages,omitempty"`
	Root        *Page    `protobuf:"bytes,7,opt,name=root,proto3" json:"root,omitempty"`
	Options     *Options `protobuf:"bytes,8,opt,name=options,proto3" json:"options,omitempty"`
	SearchId    string   `protobuf:"bytes,9,opt,name=searchId,proto3" json:"searchId,omitempty"`
}

func (x *Navi) Reset() {
	*x = Navi{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_content_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Navi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Navi) ProtoMessage() {}

func (x *Navi) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Navi.ProtoReflect.Descriptor instead.
func (*Navi) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{4}
}

func (x *Navi) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Navi) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Navi) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Navi) GetHeader() []*Page {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Navi) GetFooter() []*Page {
	if x != nil {
		return x.Footer
	}
	return nil
}

func (x *Navi) GetPages() []*Page {
	if x != nil {
		return x.Pages
	}
	return nil
}

func (x *Navi) GetRoot() *Page {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *Navi) GetOptions() *Options {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Navi) GetSearchId() string {
	if x != nil {
		return x.SearchId
	}
	return ""
}

var File_proto_content_proto protoreflect.FileDescriptor

var file_proto_content_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x70, 0x22, 0x5b, 0x0a, 0x0b, 0x50, 0x61,
	0x67, 0x65, 0x54, 0x6f, 0x63, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x26, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x61, 0x70, 0x70, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x63, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x6b, 0x0a, 0x0b, 0x50, 0x61, 0x67, 0x65, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x68, 0x74, 0x6d, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x74, 0x6d, 0x6c,
	0x12, 0x22, 0x0a, 0x03, 0x74, 0x6f, 0x63, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x61, 0x70, 0x70, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x63, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x03, 0x74, 0x6f, 0x63, 0x22, 0xa3, 0x02, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x12, 0x1f, 0x0a,
	0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61,
	0x70, 0x70, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x68, 0x6f, 0x77, 0x18, 0x14, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x04, 0x73, 0x68, 0x6f, 0x77, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x15, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x22, 0x27, 0x0a, 0x07, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x72, 0x64, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x72, 0x64,
	0x69, 0x6f, 0x6e, 0x22, 0x98, 0x02, 0x0a, 0x04, 0x4e, 0x61, 0x76, 0x69, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x52,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x06, 0x66, 0x6f, 0x6f, 0x74, 0x65,
	0x72, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x50, 0x61,
	0x67, 0x65, 0x52, 0x06, 0x66, 0x6f, 0x6f, 0x74, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x05, 0x70, 0x61,
	0x67, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x70, 0x2e,
	0x50, 0x61, 0x67, 0x65, 0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x04, 0x72,
	0x6f, 0x6f, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x70, 0x2e,
	0x50, 0x61, 0x67, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x12, 0x26, 0x0a, 0x07, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x70,
	0x70, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x49, 0x64, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x49, 0x64, 0x42, 0x09,
	0x5a, 0x07, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_content_proto_rawDescOnce sync.Once
	file_proto_content_proto_rawDescData = file_proto_content_proto_rawDesc
)

func file_proto_content_proto_rawDescGZIP() []byte {
	file_proto_content_proto_rawDescOnce.Do(func() {
		file_proto_content_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_content_proto_rawDescData)
	})
	return file_proto_content_proto_rawDescData
}

var file_proto_content_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_content_proto_goTypes = []interface{}{
	(*PageTocItem)(nil), // 0: app.PageTocItem
	(*PageContent)(nil), // 1: app.PageContent
	(*Page)(nil),        // 2: app.Page
	(*Options)(nil),     // 3: app.Options
	(*Navi)(nil),        // 4: app.Navi
}
var file_proto_content_proto_depIdxs = []int32{
	0, // 0: app.PageTocItem.items:type_name -> app.PageTocItem
	0, // 1: app.PageContent.toc:type_name -> app.PageTocItem
	2, // 2: app.Page.pages:type_name -> app.Page
	2, // 3: app.Navi.header:type_name -> app.Page
	2, // 4: app.Navi.footer:type_name -> app.Page
	2, // 5: app.Navi.pages:type_name -> app.Page
	2, // 6: app.Navi.root:type_name -> app.Page
	3, // 7: app.Navi.options:type_name -> app.Options
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_content_proto_init() }
func file_proto_content_proto_init() {
	if File_proto_content_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_content_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageTocItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_content_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_content_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Page); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_content_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Options); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_content_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Navi); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_content_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_content_proto_goTypes,
		DependencyIndexes: file_proto_content_proto_depIdxs,
		MessageInfos:      file_proto_content_proto_msgTypes,
	}.Build()
	File_proto_content_proto = out.File
	file_proto_content_proto_rawDesc = nil
	file_proto_content_proto_goTypes = nil
	file_proto_content_proto_depIdxs = nil
}
