declare const _default: (typeof PrintMedia | typeof AtPage | typeof Breaks | typeof Splits | typeof Counters | typeof Lists | typeof PositionFixed | typeof PageCounterIncrement | typeof NthOfType)[];
export default _default;
import PrintMedia from "./print-media.js";
import AtPage from "./atpage.js";
import Breaks from "./breaks.js";
import Splits from "./splits.js";
import Counters from "./counters.js";
import Lists from "./lists.js";
import PositionFixed from "./position-fixed.js";
import PageCounterIncrement from "./page-counter-increment.js";
import NthOfType from "./nth-of-type.js";
